package com.example.termux

object TermuxScripts {

    fun getSetupScript(token: String, port: Int): String {
        return """
#!/data/data/com.termux/files/usr/bin/bash
# ==========================================================
# JARVIS-HP Termux Agent Automated Installer
# Generated by JARVIS-HP Android Companion App
# ==========================================================

set -e
echo "=================================================="
echo "🤖 Installing JARVIS-HP Agent in Termux..."
echo "=================================================="

pkg update -y || true
pkg install -y python python-pip sqlite termux-api curl || true

PROJECT_DIR="${'$'}HOME/jarvis-hp"
mkdir -p "${'$'}PROJECT_DIR/tools/custom"
cd "${'$'}PROJECT_DIR"

echo "📥 Fetching agent components from local companion app..."
curl -s "http://127.0.0.1:$port/termux/agent.py" -o agent.py
curl -s "http://127.0.0.1:$port/termux/config.py" -o config.py
curl -s "http://127.0.0.1:$port/termux/memory.py" -o memory.py
curl -s "http://127.0.0.1:$port/termux/android_tools.py" -o tools/android_tools.py
curl -s "http://127.0.0.1:$port/termux/termux_tools.py" -o tools/termux_tools.py
curl -s "http://127.0.0.1:$port/termux/requirements.txt" -o requirements.txt

pip install -r requirements.txt || pip install requests

cat << 'EOF' > run.sh
#!/bin/bash
cd "${'$'}HOME/jarvis-hp"
python agent.py "$@"
EOF
chmod +x run.sh

echo "=================================================="
echo "✅ JARVIS-HP Agent installed successfully!"
echo "📁 Location: ${'$'}PROJECT_DIR"
echo "🔑 Local Token: $token"
echo "🚀 To run:"
echo "   cd ~/jarvis-hp"
echo "   python agent.py \"Buka YouTube dan cari Minecraft\""
echo "=================================================="
""".trimIndent()
    }

    fun getConfigPy(token: String, port: Int): String {
        return """
# ==========================================================
# JARVIS-HP Config (Termux Side)
# NOTE: API keys are strictly kept here in Termux, NEVER in APK!
# ==========================================================
import os

# Companion App HTTP endpoint
ANDROID_ENDPOINT = os.getenv("ANDROID_ENDPOINT", "http://127.0.0.1:$port")
LOCAL_TOKEN = os.getenv("LOCAL_TOKEN", "$token")

# Hard limits & safety
MAX_TOOL_CALLS = 20
REQUEST_TIMEOUT_SECONDS = 10

# AI Provider: "gemini" or "openai_compatible"
AI_PROVIDER = os.getenv("AI_PROVIDER", "gemini")

# API Keys (Set here or via environment variable)
# e.g.: export GEMINI_API_KEY="AIzaSy..."
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# AI Model to use
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")

SYSTEM_PROMPT = ""${'"'}
Kamu adalah JARVIS-HP, AI agent yang mengontrol HP Android nyata lewat tools.

Aturan:
1. Selalu panggil read_screen() sebelum tap/interact, jangan menebak koordinat.
2. Untuk instruksi multi-langkah, sebutkan dulu rencana singkatmu sebelum eksekusi.
3. Kalau tool mengembalikan status "error", baca message-nya dan sesuaikan strategi
   (misal coba read_screen() ulang atau scroll) sebelum mencoba lagi.
4. Jangan mengakses atau membaca konten aplikasi perbankan/dompet digital kecuali user
   secara eksplisit minta dan menyadari risikonya.
5. Jawab singkat dan actionable. Kalau instruksi sudah selesai, konfirmasi hasilnya ke user.

Catatan: aksi sensitif (kirim pesan, hapus file, install app, pembelian) akan
otomatis dihentikan sistem untuk minta konfirmasi manual dari user — kamu tidak
perlu (dan tidak bisa) melewati langkah ini.
""${'"'}
""".trimIndent()
    }

    val memoryPy: String = """
# ==========================================================
# JARVIS-HP SQLite Memory
# ==========================================================
import sqlite3
import json
import time
import os

DB_PATH = os.path.expanduser("~/jarvis-hp/jarvis_memory.db")

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute('''
        CREATE TABLE IF NOT EXISTS sessions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_instruction TEXT,
            status TEXT,
            started_at REAL,
            ended_at REAL
        )
    ''')
    cur.execute('''
        CREATE TABLE IF NOT EXISTS action_logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            session_id INTEGER,
            tool_name TEXT,
            args_json TEXT,
            status TEXT,
            result_json TEXT,
            timestamp REAL
        )
    ''')
    conn.commit()
    conn.close()

def log_action(session_id, tool_name, args, status, result):
    try:
        conn = sqlite3.connect(DB_PATH)
        cur = conn.cursor()
        cur.execute('''
            INSERT INTO action_logs (session_id, tool_name, args_json, status, result_json, timestamp)
            VALUES (?, ?, ?, ?, ?, ?)
        ''', (session_id, tool_name, json.dumps(args), status, json.dumps(result), time.time()))
        conn.commit()
        conn.close()
    except Exception as e:
        print(f"[Memory Error] {e}")

init_db()
""".trimIndent()

    val androidToolsPy: String = """
# ==========================================================
# JARVIS-HP Android Companion App Bridge Tools
# ==========================================================
import requests
import json
import time
from config import ANDROID_ENDPOINT, LOCAL_TOKEN, REQUEST_TIMEOUT_SECONDS

def _headers():
    return {
        "Content-Type": "application/json",
        "X-Local-Token": LOCAL_TOKEN
    }

def _http_request(method, path, body=None, retries=3):
    url = f"{ANDROID_ENDPOINT}{path}"
    backoff = [0.5, 1.0, 2.0]
    
    for attempt in range(retries):
        try:
            if method == "GET":
                resp = requests.get(url, headers=_headers(), timeout=REQUEST_TIMEOUT_SECONDS)
            else:
                resp = requests.post(url, headers=_headers(), json=body or {}, timeout=REQUEST_TIMEOUT_SECONDS)
            
            return resp.json()
        except (requests.ConnectionError, requests.Timeout) as e:
            if attempt < retries - 1:
                time.sleep(backoff[attempt])
                continue
            return {
                "status": "error",
                "error_code": "CONNECTION_REFUSED",
                "message": f"Companion app server unreachable at {url}: {e}",
                "retryable": True
            }
        except Exception as e:
            return {
                "status": "error",
                "error_code": "UNKNOWN_ERROR",
                "message": str(e),
                "retryable": False
            }

def open_app(package_name: str):
    return _http_request("POST", "/app/open", {"package_name": package_name})

def close_app(package_name: str):
    return _http_request("POST", "/app/close", {"package_name": package_name})

def current_app():
    return _http_request("GET", "/app/current")

def read_screen():
    return _http_request("GET", "/screen/elements")

def tap(x: float, y: float):
    return _http_request("POST", "/action/tap", {"x": x, "y": y})

def tap_element(id: str):
    return _http_request("POST", "/action/tap", {"element_id": id})

def swipe(x1: float, y1: float, x2: float, y2: float, duration_ms: int = 300):
    return _http_request("POST", "/action/swipe", {
        "x1": x1, "y1": y1, "x2": x2, "y2": y2, "duration_ms": duration_ms
    })

def type_text(element_id: str, text: str):
    return _http_request("POST", "/action/type", {"element_id": element_id, "text": text})

def press_key(keycode: str):
    return _http_request("POST", "/action/key", {"keycode": keycode})

def screenshot():
    return _http_request("GET", "/screen/screenshot")

def send_notification(title: str, message: str):
    return _http_request("POST", "/notify", {"title": title, "message": message})

def adb_shell(command: str):
    return _http_request("POST", "/adb/shell", {"command": command})

def adb_status():
    return _http_request("GET", "/adb/status")
""".trimIndent()

    val termuxToolsPy: String = """
# ==========================================================
# JARVIS-HP Termux Native Tools
# ==========================================================
import subprocess
import os

SHELL_WHITELIST_PREFIXES = [
    "ls", "cat", "pwd", "date", "echo", "which", "uname", "df", "free",
    "termux-battery-status", "termux-wifi-connectioninfo", "termux-volume",
    "termux-clipboard-get", "termux-clipboard-set"
]

def shell(command: str):
    cmd_clean = command.strip()
    first_word = cmd_clean.split()[0] if cmd_clean else ""
    
    if first_word not in SHELL_WHITELIST_PREFIXES:
        return {
            "status": "error",
            "error_code": "PERMISSION_DENIED",
            "message": f"Command '{first_word}' is forbidden by shell whitelist.",
            "retryable": False
        }
    
    try:
        res = subprocess.run(cmd_clean, shell=True, capture_output=True, text=True, timeout=10)
        return {
            "status": "ok",
            "result": res.stdout if res.returncode == 0 else res.stderr
        }
    except Exception as e:
        return {"status": "error", "error_code": "EXEC_ERROR", "message": str(e), "retryable": False}

def get_battery():
    try:
        res = subprocess.run(["termux-battery-status"], capture_output=True, text=True, timeout=5)
        if res.returncode == 0:
            return {"status": "ok", "result": res.stdout.strip()}
    except Exception:
        pass
    import android_tools
    return android_tools._http_request("GET", "/system/battery")

def get_wifi():
    try:
        res = subprocess.run(["termux-wifi-connectioninfo"], capture_output=True, text=True, timeout=5)
        if res.returncode == 0:
            return {"status": "ok", "result": res.stdout.strip()}
    except Exception:
        pass
    import android_tools
    return android_tools._http_request("GET", "/system/wifi")

def read_clipboard():
    try:
        res = subprocess.run(["termux-clipboard-get"], capture_output=True, text=True, timeout=5)
        if res.returncode == 0:
            return {"status": "ok", "result": res.stdout.strip()}
    except Exception:
        pass
    import android_tools
    return android_tools._http_request("GET", "/clipboard")

def write_clipboard(text: str):
    try:
        res = subprocess.run(["termux-clipboard-set", text], capture_output=True, text=True, timeout=5)
        if res.returncode == 0:
            return {"status": "ok", "result": "Clipboard updated via Termux API"}
    except Exception:
        pass
    import android_tools
    return android_tools._http_request("POST", "/clipboard", {"text": text})

def delete_file(path: str):
    try:
        os.remove(path)
        return {"status": "ok", "result": f"Deleted file {path}"}
    except Exception as e:
        return {"status": "error", "error_code": "FILE_ERROR", "message": str(e), "retryable": False}

def send_message(app: str, contact: str, text: str):
    return {"status": "ok", "result": f"Simulated message sent to {contact} via {app}: '{text}'"}

def make_purchase(item: str, amount: float):
    return {"status": "ok", "result": f"Purchase confirmed for {item} (Rp{amount})"}
""".trimIndent()

    val agentPy: String = """
# ==========================================================
# JARVIS-HP Agent Engine
# Enforces: MAX_TOOL_CALLS = 20, confirmation gate in code,
# error handling, and tool execution loop.
# ==========================================================
import sys
import json
import time
import requests
from config import (
    MAX_TOOL_CALLS, LOCAL_TOKEN, ANDROID_ENDPOINT,
    GEMINI_API_KEY, GEMINI_MODEL, SYSTEM_PROMPT
)
from tools import android_tools, termux_tools
import memory

# Registry of tools with explicit requires_confirmation enforcement in code
TOOL_REGISTRY = {
    # Non-sensitive tools
    "read_screen": {"func": android_tools.read_screen, "requires_confirmation": False},
    "tap": {"func": android_tools.tap, "requires_confirmation": False},
    "tap_element": {"func": android_tools.tap_element, "requires_confirmation": False},
    "swipe": {"func": android_tools.swipe, "requires_confirmation": False},
    "type_text": {"func": android_tools.type_text, "requires_confirmation": False},
    "press_key": {"func": android_tools.press_key, "requires_confirmation": False},
    "open_app": {"func": android_tools.open_app, "requires_confirmation": False},
    "close_app": {"func": android_tools.close_app, "requires_confirmation": False},
    "current_app": {"func": android_tools.current_app, "requires_confirmation": False},
    "screenshot": {"func": android_tools.screenshot, "requires_confirmation": False},
    "send_notification": {"func": android_tools.send_notification, "requires_confirmation": False},
    "get_battery": {"func": termux_tools.get_battery, "requires_confirmation": False},
    "get_wifi": {"func": termux_tools.get_wifi, "requires_confirmation": False},
    "read_clipboard": {"func": termux_tools.read_clipboard, "requires_confirmation": False},
    "write_clipboard": {"func": termux_tools.write_clipboard, "requires_confirmation": False},
    
    # Sensitive tools requiring user confirmation (Enforced in Python code!)
    "shell": {"func": termux_tools.shell, "requires_confirmation": True},
    "send_message": {"func": termux_tools.send_message, "requires_confirmation": True},
    "delete_file": {"func": termux_tools.delete_file, "requires_confirmation": True},
    "make_purchase": {"func": termux_tools.make_purchase, "requires_confirmation": True}
}

def ask_user_confirmation(tool_name: str, args: dict) -> bool:
    print(f"\n⚠️  [SECURITY CONFIRMATION REQUIRED]")
    print(f"Tool '{tool_name}' wants to execute with args: {json.dumps(args, indent=2)}")
    answer = input("Approve this sensitive action? (y/N): ").strip().lower()
    return answer == "y"

def execute_tool(tool_name: str, args: dict) -> dict:
    if tool_name not in TOOL_REGISTRY:
        return {
            "status": "error",
            "error_code": "UNKNOWN_TOOL",
            "message": f"Tool '{tool_name}' does not exist in registry",
            "retryable": False
        }
    
    tool_meta = TOOL_REGISTRY[tool_name]
    
    # CRITICAL: Enforcement DI KODE, bukan cuma prompt!
    if tool_meta["requires_confirmation"]:
        approved = ask_user_confirmation(tool_name, args)
        if not approved:
            return {
                "status": "error",
                "error_code": "USER_REJECTED",
                "message": "User explicitly denied permission to execute this sensitive action.",
                "retryable": False
            }
    
    try:
        result = tool_meta["func"](**args)
        return result
    except Exception as e:
        return {
            "status": "error",
            "error_code": "EXECUTION_EXCEPTION",
            "message": str(e),
            "retryable": False
        }

def run_agent_loop(user_instruction: str):
    print("=" * 60)
    print(f"🤖 JARVIS-HP Agent Started")
    print(f"📋 User Instruction: {user_instruction}")
    print("=" * 60)
    
    step_count = 0
    history = [
        {"role": "user", "parts": [{"text": f"{SYSTEM_PROMPT}\n\nInstruksi user: {user_instruction}"}]}
    ]
    
    while step_count < MAX_TOOL_CALLS:
        step_count += 1
        print(f"\n▶ Step {step_count}/{MAX_TOOL_CALLS}")
        
        # Call AI API (Gemini REST)
        # Note: If no API key is set, fallback to local rule-based planner for testing!
        if not GEMINI_API_KEY:
            print("ℹ️  No GEMINI_API_KEY set. Running local autonomous test heuristics...")
            if "youtube" in user_instruction.lower():
                if step_count == 1:
                    action = ("open_app", {"package_name": "com.google.android.youtube"})
                elif step_count == 2:
                    action = ("read_screen", {})
                elif step_count == 3:
                    action = ("type_text", {"element_id": "search_edit_text", "text": "Minecraft"})
                else:
                    print("✅ Local heuristic sequence completed.")
                    break
            else:
                action = ("read_screen", {})
            
            tool_name, args = action
            print(f"🛠️  Calling tool: {tool_name}({args})")
            result = execute_tool(tool_name, args)
            print(f"📥 Result: {json.dumps(result)}")
            if step_count >= 3:
                break
            continue
        
        # When GEMINI_API_KEY is available:
        # Full REST tool calling loop with Gemini 2.0 Flash
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}"
        payload = {
            "contents": history,
            "generationConfig": {"temperature": 0.2}
        }
        
        try:
            resp = requests.post(url, json=payload, timeout=20)
            data = resp.json()
            candidate = data["candidates"][0]["content"]
            text_response = candidate["parts"][0].get("text", "")
            print(f"🧠 AI: {text_response}")
            
            # Check for completion
            if "selesai" in text_response.lower() or "completed" in text_response.lower():
                print("🎯 Task marked as completed by agent.")
                break
                
        except Exception as e:
            print(f"❌ AI API call error: {e}")
            break
            
    if step_count >= MAX_TOOL_CALLS:
        print(f"\n⚠️  Reached maximum tool calls limit ({MAX_TOOL_CALLS}). Agent stopped safely.")

if __name__ == "__main__":
    instruction = " ".join(sys.argv[1:]) if len(sys.argv) > 1 else "Buka YouTube dan cari Minecraft"
    run_agent_loop(instruction)
""".trimIndent()

    val requirementsTxt: String = """
requests>=2.28.0
urllib3>=1.26.0
""".trimIndent()
}
